trigger:
  branches:
    include:
    - master
  
pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  packageProjectPath: 'src\DoTheSpriteThing\DoTheSpriteThing.csproj'
  testsProjectPath: 'test\DoTheSpriteThing.Tests\DoTheSpriteThing.Tests.csproj'
  
steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: '6a974ad4-691c-4139-ab48-af9c2c69a028'
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build'    
- script: dotnet test $(testsProjectPath) --configuration $(buildConfiguration) --filter TestCategory!=AutomationTests --no-build
  displayName: 'Run tests'  
- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(packageProjectPath)'
    nobuild: true
    versioningScheme: 'off'    
- task: PublishBuildArtifacts@1
  displayName: 'Publish deployment artifacts'