trigger:
  branches:
    include:
    - master
  
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  packageProjectPath: 'src\DoTheSpriteThing\DoTheSpriteThing.csproj'
  testsProjectPath: 'test\DoTheSpriteThing.Tests\DoTheSpriteThing.Tests.csproj'
  packageOutputPath: '$(Build.ArtifactStagingDirectory)/DoTheSpriteThing'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
    projects: |
      $(packageProjectPath)
      $(testsProjectPath)
    feedsToUse: 'select'
    feedRestore: 'phwebsitedesign'
    verbosityRestore: 'Normal'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    packages: '$(testsProjectPath)'
    arguments: '--no-restore --configuration $(buildConfiguration) --filter TestCategory!=AutomationTests'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '$(packageProjectPath)'
    outputDir: '$(packageOutputPath)'
    includeSymbols: true
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet package'  
  inputs:
    command: 'push'
    searchPatternPush: '$(packageOutputPath)/*.nupkg'
    feedPublish: 'phwebsitedesign'